permalink:           pretty

# Setup
title:               Manifesto of a Fuckin' Champ
tagline:             Who we are and what we strive for 
description:         There is a particular type of excellent person we choose to call a Fuckin' Champ. Here we define this kind of humble greatness that we aspire to.
url:                 http://manifesto.fuckinchamp.fyi
baseurl:             ''
include: [".well-known"]

# About/contact
author:
  name:              JP Hastings-Spital
  url:               https://twitter.com/jphastings

# Custom vars
version:             1.0
